change bootstrap script to auto update wpa-e certs

diff --git a/demos/wifi/wpa_enterprise/certs/bootstrap b/demos/wifi/wpa_enterprise/certs/bootstrap
--- a/demos/wifi/wpa_enterprise/certs/bootstrap
+++ b/demos/wifi/wpa_enterprise/certs/bootstrap
@@ -19,11 +19,18 @@ make -h > /dev/null 2>&1
 #  If we have a working "make", then use it.  Otherwise, run the commands
 #  manually.
 #
-if [ "$?" = "0" ]; then
-  make all
-  exit $?
-fi
+# removed by WES 20210416 for just updating ca/certs/key
+# if [ "$?" = "0" ]; then
+#   make all
+#   exit $?
+# fi
 
+# remove old certs files, add by WES 20210416
+echo "==>Remove old certs files..."
+rm -f *.pem *.der *.csr *.crt *.key *.p12 serial* index.txt*
+echo ""
+
+echo "==>Start to create radius certs..."
 #
 #  The following commands were created by running "make -n", and edited
 #  to remove the trailing backslash, and to add "exit 1" after the commands.
@@ -80,3 +87,29 @@ fi
 if [ ! -f client.crt ]; then
   openssl ca -batch -keyfile ca.key -cert ca.pem -in client.csr  -key `grep output_password ca.cnf | sed 's/.*=//;s/^ *//'` -out client.crt -extensions xpclient_ext -extfile xpextensions -config ./client.cnf
 fi
+
+# add by WES 20210416 for client.pem,  client_rsa.key
+echo "==>Generate client.pem"
+if [ -f client.crt ]; then
+  openssl x509 -in client.crt -out client.pem
+else
+  echo "*** generate client.pem error, because client.crt not created!"
+  exit 1
+fi
+echo ""
+
+echo "==>Generate client_rsa.key"
+if [ -f client.key ]; then
+  openssl rsa -in client.key -out client_rsa.key -passin pass:`grep output_password client.cnf | sed 's/.*=//;s/^ *//'`
+else
+  echo "*** generate client_rsa.key error, because client.key not created!"
+  exit 1
+fi
+echo ""
+echo "==>Success!"
+
+echo "NOTE1: update your server certs by copy '../certs/' into '/usr/local/etc/raddb/'"
+# NOTE: change your target dir
+#cp -Rf ../certs /usr/local/etc/raddb/
+
+echo "NOTE2: update your device certs(rootca/client_cert/key)."
